### ISSUE TITLE
Linux対応してほしい。

### ISSUE THREAD

**Issue by NaokiSato102** [Aivis-Project/AivisSpeech#3]
## 内容

無料合成音声を無料OSで動かしたい。

**Comment by tsukumijima** [comment]
AivisSpeech は少人数で開発しており、現時点では Linux 版のサポートを行える状況にないのが現状です。
私自身 Linux デスクトップ関連の知識がなく、さらにフォーク元の VOICEVOX からは様々なカスタマイズが行われているため、ビルドできたとして動作するかは不明です。
また、同じ Linux でも様々な環境が存在し、サポートコストが増大するおそれもあります。その割にはユーザーは少なく、

以上の理由から、現時点で AivisSpeech の Linux 版をリリースする予定はありません。
サポートリソースなどが増加した場合、全体のユーザー数が増えた場合は、再度検討する可能性はあります。
