### ISSUE TITLE
Bug = 音声合成モデルの管理 - ボイスサンプルはどのモデルでも同じ声が出る。

### ISSUE THREAD

**Issue by ckjpn** [Aivis-Project/AivisSpeech#7]
Bug = 音声合成モデルの管理 - ボイスサンプルはどのモデルでも同じ声が出る。

This is a demo video. Turn on the sound.
https://github.com/user-attachments/assets/af873d13-e422-438e-b32f-382a19d2d647

**Comment by tsukumijima** [comment]
この不具合はすでに認識しており、開発版ではすでに修正済みです。次回バージョンアップにて反映されます。
